name: Test Email Step

on:
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 24f2009009@ds.study.iitm.ac.in
        run: echo "Hello, world!"
